### ISSUE TITLE
IE11: dropdown items truncated

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#336]
## Description

Page-size-select's dropdown truncated in paginated demo page/IE11 only.
This is also the case with the actions dropdown.
Other browsers look fine.

## Version
data-grid tag: 1.0.3
Browsers:  IE11

## Screenshot
![2018-01-12_1744](https://user-images.githubusercontent.com/10835611/34901590-0479b868-f7c1-11e7-8d75-c51011fb6fbd.png)

**Comment by alump** [comment]
We have already asked this to be fixed in px-dropdown, it's not bug in px-data-grid.

**Comment by Aileen-H** [comment]
1/16/18: Agreed to increase the width of the dropdown. Override minimum width - px-button.

**Comment by Aileen-H** [comment]
Dropdown fix by GE and will let Vaadin know.

**Comment by randyaskin** [comment]
I removed the min-width from the button in px-dropdown, if you remove any width definition in the data-grid it should handle the sizing automatically.

**Comment by randyaskin** [comment]
While you're looking at it, could you also turn on the `disable-clear` property of this px-dropdown, as something should always be selected for page size and the button doesn't work in this case anyway.

**Comment by alump** [comment]
I still had same issue with IE11 with new code.

**Comment by alump** [comment]
@randyaskin - check the PR, what I am doing wrong, it still has same issue with IE11.

**Comment by ppeyro** [comment]
This is still happening with V1.2.3 in IE11.  We should reopen it.

**Comment by alump** [comment]
I will write ie11 specific CSS trick to resolve this

**Comment by limonte** [comment]
It would be great to get a proper fix from GE team instead of bringing more tricks, reported https://github.com/PredixDev/px-dropdown/issues/77

**Comment by randyaskin** [comment]
I fought with this for an additional 3 hours this morning, I can't figure out why iron-dropdown assigns a different max-width in IE than it does in other browsers. I tried adjusting padding to a whole-rem value (IE rounds 0.6667rem to 0.66rem instead), changing box-sizing, manually overriding width and max-width in various places, etc and nothing worked.

As a workaround, I've added a property for `disable-truncate` in v4.7.0 of px-dropdown that turns off truncation - items longer than the maximum width will wrap instead of truncating, and short items like the page size dropdown will appear as spec'ed if `disable-truncate` is set.
