### ISSUE TITLE
Advanced Filter:  Timezone may throw the date off.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#654]
## Description

Dates can be thrown off since we don't seem to be able to set a timezone. I think it  defaults to GMT, so for example, in filters when you select the range picker, today's date is already set to 2/13 instead of 2/12.

Also noticed setting the filter to start at 1/1/2000, will show it as 12/31/1999 in the filter chip.

Don't see an option documented for setting the corresponding timezone, so assuming there is no way to do it.

## Version
Data-grid: V1.2.1

## Screenshot
![screen shot 2018-02-12 at 6 11 16 pm](https://user-images.githubusercontent.com/10835611/36130198-478e11f4-1020-11e8-9a43-5e53a84d98c3.png)

![screen shot 2018-02-12 at 6 16 21 pm](https://user-images.githubusercontent.com/10835611/36130297-e8b15032-1020-11e8-8eb3-5385918e4913.png)

![screen shot 2018-02-12 at 6 15 55 pm](https://user-images.githubusercontent.com/10835611/36130299-ec27928a-1020-11e8-9826-e49dfd80dcce.png)

**Comment by alump** [comment]
@ppeyro  If you check your first screenshot, it say UTC in your rangepicker. So works as planned?

And spec told to show dates in chips, not names of ranges. So that's new feature (not trivial as now we would need to store some metadata to filter rules too). Also filters will have actual dates, so if you store filter, and reuse it later, it will be same days not updated to current day. So using name is bad idea.

**Comment by ppeyro** [comment]
@alump  Yes, thanks for pointing out the UTC timezone. So the point of the issue was I don't think there is a way we can set/overwrite the timezone when specifying a date-type column, or is there? 
I suspect customers would want to be able to define their timezone. For example, if the data is coming into the grid as say GMT and in the data-grid it assumes it's UTC, wouldn't it cause problems/confusion like what I mentioned above?

Also, the 2nd issue is:  there is a discrepancy between what the filter is defined as in the modal vs. what's shown in the chip. Modal defines the range as Jan/1/2000 to Jan/1/2018, but the filter chip shows it as Dec/31/1999 to Dec/31/2017. I thought maybe this had something to do with the timezone, so I dumped that in the same issue. If it's confusing we can separate them out.

**Comment by alump** [comment]
@ppeyro In modal you have selector for timezone, see the UTC there. That's why it's in different timezone. Can not accept these bugs as this behavior is not specified anywhere. When specifications are done, then feature request issue should be made. Eg. what should be default timezone in editors, filters and chips. But having now issue tickets for all different parts of UI is not acceptable idea.

**Comment by ppeyro** [comment]
@alump  Please reopen this one as well.  There are issues in here we need to address before release. If you can't do the implementation, that doesn't mean the issue can go away!!  Please reopen so we can discuss who will take ownership.

**Comment by alump** [comment]
Depending #679

**Comment by alump** [comment]
Original issue report is not backed up by specifications, and so needs to be rewritten once wanted behavior is specified. Only case when it will be valid would be if UTC is defined as default presentation timezone, and test case have not overridden that value.

**Comment by andrealperry** [comment]
Needed for beta

**Comment by davidrleonard** [comment]
Recheck after timezone fix.
