### ISSUE TITLE
Advanced Filter: Filtering based on dates results unpredictable in Safari10, IE11.

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#661]
## Description

When filtering based on a date column, the results seem to be different if you use Chrome & FF vs, Safari10 and IE11.
Not getting any rows returned in Safari10 & IE11 even though there are rows returned in Chrome for example.
I've also tried switching the dataFormat to ISO vs. "YYYY-MM-DD HH:mm:ss"

## Version
Data-grid: V1.2.1-1.2.3
Browsers: Safari10 & IE11 exhibiting the issue, Chrome and FF58 work as expected.

## Screenshots
The filter used is in the screenshot below:
![screen shot 2018-02-13 at 6 08 10 pm](https://user-images.githubusercontent.com/10835611/36184682-08bb3c3e-10ea-11e8-8773-fa3edaa8d248.png)

![screen shot 2018-02-13 at 6 07 38 pm](https://user-images.githubusercontent.com/10835611/36184835-faa04be8-10ea-11e8-8722-978f554b1781.png)

## Code
https://gist.github.com/ppeyro/753ae83008141035a3e9b68eb27c043e

**Comment by alump** [comment]
These are the timezone issues, you have UTC selected on your filters, but those chips show time with your local time, you are 5 hours behind.

So summary midnight January 1st in UTC, is about 6 hours before midnight December 31 in pacific time (too lazy to check which was the actual hour amount at that time of year).

Closing is as works as expected (read: functionality not defined, so using local time is fine). There should be enhancement issue that defines all the different places and how timezones should behave there, this is not a issue, it's a new feature.

**Comment by ppeyro** [comment]
@alump  Please reopen the issue. We need to address this issue before releasing.  I think our team may be taking this on, so this issue is to serve as the tracker.

**Comment by alump** [comment]
Depending #679

**Comment by alump** [comment]
The original description has nothing to do with this issue.

Behavior is predictable, it's just not defined by specifications:
- Filter date range has option to select timezone. If you select UTC, then time is read as UTC
- In chips there are no timezone presentation, and value is in user's local timezone
- This is why time you put into filter can be different than value you see in chips.

The actual issue is in ticket #679, all this haven't been specified. For this reason current behavior (how bad it might be) is as valid as expectation in issue ticket. When specification is done, then issues can be reported, but even then the current behavior would be correct. If user's own local timezone is selected as presentation timezone, and UTC is selected in filtering range picker.

**Comment by ppeyro** [comment]
The issue is specific to 2 browsers only. If this is the intended behavior,  it should be consistent across all browsers and not behaving differently in safari10 & IE11.

**Comment by andrealperry** [comment]
Needed for Beta

**Comment by davidrleonard** [comment]
Need to recheck after timezone fix.
