### ISSUE TITLE
Autofilter can't handle parsing /

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#754]
## Description

Using autofilter to search for a date containing "/" returns no results even though there are rows to be returned.
Reproducible in the demo: 

- Enable auto-filter
- Search for 03, the correct rows are returned.
- Now search for 03/, no rows returned.

## Version
Data-grid: Branch origin/feature/timezones
Browser: Chrome

## Screenshots
![screen shot 2018-03-09 at 4 43 05 pm](https://user-images.githubusercontent.com/10835611/37236062-fb01900c-23b8-11e8-8a49-8f3f48040dad.png)

**Comment by drewharvey** [comment]
This happens in the master branch as well.  It is not caused by the timezone implementation.  The issue here is that filtering happens on the underlying data.  If you change the `displayFormat` of the dates, then what you see in the column actually isn't the same as the underlying data.  In this case, the data is actually formatted with dashes.

**Comment by ppeyro** [comment]
Thanks @drewharvey.  
Checked with our design team and they agree this will be a usability issue. At a minimum, filtering should be able to filter on - and / for date columns when `<displayFormat>` changes the format to / instead of - .   Could you please comment on how much effort this will be to fix?

**Comment by drewharvey** [comment]
1-3 days.

Only enabling this type of filtering for dates/times would probably be a few days because we can expect some kind of regression.  Most likely the implementation is more complex than it appears on the surface.  The auto-filter will need to be aware of the renderers and how to convert data using them.  This will also have a massive performance hit because now you are re-rendering every single row in order to compare it against the auto-filter value.  If you have a large amount of rows, this could be slow.

Note: Filtering on display value only for the date column also brings inconsistencies.  The reason this filter works on the underlying data is because we don't know how things will be rendered.  Maybe you show an image/icon based on the data, and then how do you filter on those?  One approach would be to have an API where the application defines how filtering for that row gets handled.  This way the application can define a special renderer and also define how the auto-filter values should be compared to the data.  Of course this is a larger change with impact on the entire auto filter functionality.

**Comment by ppeyro** [comment]
Team feels that users could use advanced filtering for more specific searches and auto filter should remain as the raw data search tool and not worry about DisplayFormat complexity.  
Closing.
