### ISSUE TITLE
TimeZone: Editing a date column with timestamps+seconds triggers an empty state in calendar picker

### ISSUE THREAD

**Issue by ppeyro** [predixdesignsystem/px-data-grid#756]
## Description

When you go into edit mode, a date column that contains seconds and timezone doesn't retain its value. 
Note:
- Tested this without seconds and the calendar picker retains its value when you go into edit mode.

This is reproducible in the demo with a slight tweak, change the display format and dateFormat to include :ss (In addition to the current HH:mm).

## Version
Data-grid:origin/feature/timezones
Browser: Chrome

## Screenshots
<img width="918" alt="screen shot 2018-03-09 at 5 25 21 pm" src="https://user-images.githubusercontent.com/10835611/37236666-de84d71c-23be-11e8-905b-39c63be2427e.png">

**Comment by drewharvey** [comment]
After investigating further, I've found this issue to be invalid.  The issue here is that you've specified the `dateFormat.format` to include seconds (`ss`) but the actual data does not include seconds.  The actual data format must match the `dateFormat.format`, that is the entire point of the `dateFormat.format` property.

Closing this, works as expected.

**Comment by ppeyro** [comment]
Thanks @drewharvey . Verified adding seconds to `<dateFormat>` as well as the actual data resolves the issue.
