### ISSUE TITLE
Add transpilation and optimization (minification, etc) to build pipeline

### ISSUE THREAD

**Issue by evanjd** [predixdesignsystem/px-data-grid#812]
px-data-grid currently serves the development versions of polymer components to component consumers.

To be consistent with other components, and to reduce integration effort for px-data-grid users on legacy browsers, we should transpile px-data-grid JS down to ES5 so that it works on all target browsers out-of-the-box.

**Comment by evanjd** [comment]
CC @sebastiantb, I understand you've had to transpile the component JS on your project for IE11 users. If there's interest in deferring that to the component (ie. making it so that component always serves transpiled/IE11 friendly code) let me know.

**Comment by mdwragg** [comment]
That's a bad idea... minification and transpilation are an app concern, not that of the component.

**Comment by sebastiantb** [comment]
Hey evan thanks for the help,  solving this issue really helped us out.

Right now, we have a transpilation gulp task that grabs the bundled elements.html and transpile the javascript. we are serving 2 versions of the javascript one in es6 for browsers that supports it and the other in  es5 for browsers that do not support that feature. We also had to add webpack css post processing plugins in order to make the elements display styling correctly.  maybe we can add some a wiki page at the main page showcasing how to successfully transpile these components. steven davie told me you need to add support to ie 11 as well. Let me know if you need any help.

**Comment by sebastiantb** [comment]
there are more components that are written in es6, I think changing all of them will be a lot of work

**Comment by evanjd** [comment]
@mdwragg Hi! Fair call. I guess the issue here is the inconsistency with how we distribute components. [Some transpile](https://github.com/predixdesignsystem/px-tile/blob/master/gulpfile.js#L129), some don't. I'm fine with just picking one and standardising on that.

**Comment by mdwragg** [comment]
Yeah, I’m surprised the maintainers did this, it certainly wouldn’t have happened back in the day. Thoughts maintainers?

**Comment by evanjd** [comment]
No comments from the broader group, closing as I agree it's a bad idea. Have asked for this to be raised at next PDS meeting.
